const resDataMap=[
    {
        id:1,
        date:"2020/07/20",
        pickup_time:"13:00",
        boardingPlace:"高島平",
        destination:"田端",
        passengerCount:"1",
        reservationStatus:"OK"
    },
    {
        id:2,
        date:"2020/07/21",
        pickup_time:"13:00",
        boardingPlace:"高島平",
        destination:"赤羽",
        passengerCount:"2",
        reservationStatus:"NG"
    },    
    {
        id:3,
        date:"2020/07/22",
        pickup_time:"13:00",
        boardingPlace:"北赤羽",
        destination:"池袋",
        passengerCount:"3",
        reservationStatus:"NG"
    },
    {
        id:4,
        date:"2020/07/23",
        pickup_time:"13:00",
        boardingPlace:"中村橋",
        destination:"池袋",
        passengerCount:"4",
        reservationStatus:"確認中"
    },
    {
        id:5,
        date:"2020/07/24",
        pickup_time:"13:00",
        boardingPlace:"池袋",
        destination:"田端",
        passengerCount:"5",
        reservationStatus:"確認中"
    },
    {
        id:6,
        date:"2020/07/25",
        pickup_time:"13:00",
        boardingPlace:"王子",
        destination:"田端",
        passengerCount:"6",
        reservationStatus:"予約取消"
    },
    {
        id:7,
        date:"2020/07/26",
        pickup_time:"13:00",
        boardingPlace:"高島平",
        destination:"王子",
        passengerCount:"5",
        reservationStatus:"乗車完了"
    },
    {
        id:8,
        date:"2020/07/27",
        pickup_time:"13:00",
        boardingPlace:"高島平",
        destination:"蔵前",
        passengerCount:"4",
        reservationStatus:"未乗車"
    },
    {
        id:9,
        date:"2020/07/28",
        pickup_time:"13:00",
        boardingPlace:"高島平",
        destination:"田端",
        passengerCount:"3",
        reservationStatus:"OK"
    },
    {
        id:10,
        date:"2020/07/29",
        pickup_time:"13:00",
        boardingPlace:"高島平",
        destination:"赤羽",
        passengerCount:"2",
        reservationStatus:"NG"
    },    
    {
        id:11,
        date:"2020/07/30",
        pickup_time:"13:00",
        boardingPlace:"北赤羽",
        destination:"池袋",
        passengerCount:"1",
        reservationStatus:"NG"
    },
    {
        id:12,
        date:"2020/07/31",
        pickup_time:"13:00",
        boardingPlace:"中村橋",
        destination:"池袋",
        passengerCount:"2",
        reservationStatus:"確認中"
    },
    {
        id:13,
        date:"2020/08/01",
        pickup_time:"13:00",
        boardingPlace:"池袋",
        destination:"田端",
        passengerCount:"3",
        reservationStatus:"確認中"
    },
    {
        id:14,
        date:"2020/08/02",
        pickup_time:"13:00",
        boardingPlace:"王子",
        destination:"田端",
        passengerCount:"4",
        reservationStatus:"予約取消"
    },
    {
        id:15,
        date:"2020/08/03",
        pickup_time:"13:00",
        boardingPlace:"高島平",
        destination:"王子",
        passengerCount:"5",
        reservationStatus:"乗車完了"
    },
    {
        id:16,
        date:"2020/08/04",
        pickup_time:"13:00",
        boardingPlace:"高島平",
        destination:"蔵前",
        passengerCount:"6",
        reservationStatus:"未乗車"
    }
    
]

export default resDataMap